version: '3.4'

services:
  webtelemetry:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - AppSettings__OtelEndpoint=http://otel:4317
      - ZIPKIN_HOSTNAME=zipkin
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  workertelemetry:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__OtelEndpoint=http://otel:4317
      - ZIPKIN_HOSTNAME=zipkin
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
